apiVersion: apps/v1
kind: Deployment
metadata:
  name: reddit-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reddit-app
  template:
    metadata:
      labels:
        app: reddit-app
    spec:
      containers:
        - name: reddit-app
          image: reddit-app:latest  # local Docker image name
          imagePullPolicy: Never    # important when using `minikube image load`
          ports:
            - containerPort: 8000   # match EXPOSE in Dockerfile
