apiVersion: v1
kind: Service
metadata:
  name: reddit-service
spec:
  type: NodePort
  selector:
    app: reddit-app  # Match the label in your deployment
  ports:
    - protocol: TCP
      port: 80           # External access port (default HTTP)
      targetPort: 8000   # Inside container (FastAPI runs on 8000)
      nodePort: 30000    # Port exposed on your host machine
